"""add_reason_to_intervention_log

Revision ID: 61011d77efc7
Revises: a9df95bc2767
Create Date: 2026-04-23 16:15:00.542017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61011d77efc7'
down_revision: Union[str, None] = 'a9df95bc2767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervention_logs', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intervention_logs', 'reason')
    # ### end Alembic commands ###
