"""Add question types and expand interaction history

Revision ID: 957b3738967e
Revises: a2d0b6bb81e9
Create Date: 2025-09-06 13:37:42.459792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957b3738967e'
down_revision: Union[str, None] = 'a2d0b6bb81e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interaction_logs', 'bkt_prob_change')
    op.drop_column('interaction_logs', 'user_feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction_logs', sa.Column('user_feedback', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('interaction_logs', sa.Column('bkt_prob_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
