"""Consolidate interaction log structure

Revision ID: d67a18d1e658
Revises: 957b3738967e
Create Date: 2025-09-06 21:43:02.057274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd67a18d1e658'
down_revision: Union[str, None] = '957b3738967e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction_logs', sa.Column('hint_shown', sa.Boolean(), nullable=True))
    op.add_column('interaction_logs', sa.Column('hint_style_used', sa.String(), nullable=True))
    op.add_column('interaction_logs', sa.Column('user_feedback_rating', sa.Integer(), nullable=True))
    op.add_column('interaction_logs', sa.Column('bkt_change', sa.Float(), nullable=True))
    op.drop_column('interaction_logs', 'action')
    op.drop_column('interaction_logs', 'hint_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction_logs', sa.Column('hint_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('interaction_logs', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('interaction_logs', 'bkt_change')
    op.drop_column('interaction_logs', 'user_feedback_rating')
    op.drop_column('interaction_logs', 'hint_style_used')
    op.drop_column('interaction_logs', 'hint_shown')
    # ### end Alembic commands ###
