# app/models/user.py
from sqlalchemy import (
    BigInteger,
    Column,
    Integer,
    String,
    Float,
    DateTime,
    ForeignKey,
    JSON,
    Text,
    Boolean,
)
from sqlalchemy.orm import declarative_base, relationship
from datetime import datetime
from app.utils.config import settings


Base = declarative_base()


class User(Base):
    __tablename__ = "users"
    id = Column(String, primary_key=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    preferences = Column(JSON, default=lambda: {
        "hint_style_preference": "adaptive",
        "intervention_preference": "manual"
    })
    feedback_scores = Column(JSON, default=lambda: {})

    # Relationships
    skill_mastery = relationship("SkillMastery", back_populates="user", cascade="all, delete-orphan")
    interaction_logs = relationship("InteractionLog", back_populates="user", cascade="all, delete-orphan")
    exam_session = relationship("ExamSession", back_populates="user", uselist=False, cascade="all, delete-orphan")
    action_logs = relationship("UserActionLog", back_populates="user", cascade="all, delete-orphan")
    chat_logs = relationship("ChatLog", back_populates="user", cascade="all, delete-orphan")
    intervention_logs = relationship("InterventionLog", back_populates="user", cascade="all, delete-orphan")


class SkillMastery(Base):
    __tablename__ = "skill_mastery"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, ForeignKey("users.id"))
    skill_id = Column(String, index=True)
    mastery_level = Column(Float, default=settings.bkt_p_l0)
    consecutive_errors = Column(Integer, default=0)
    consecutive_skips = Column(Integer, default=0)
    last_updated = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationship
    user = relationship("User", back_populates="skill_mastery")


class InteractionLog(Base):
    __tablename__ = "interaction_logs"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, ForeignKey("users.id"))
    timestamp = Column(DateTime, default=datetime.utcnow)
    question_id = Column(Integer)
    skill = Column(String)
    
    # Answer details
    user_answer = Column(Text, nullable=True)
    is_correct = Column(Boolean, nullable=True)
    time_taken_ms = Column(Integer, nullable=True)

    # Hint and feedback details (for a single interaction loop)
    hint_shown = Column(Boolean, default=False)
    hint_style_used = Column(String, nullable=True)
    hint_text = Column(Text, nullable=True) # <-- ADDED
    user_feedback_rating = Column(Integer, nullable=True) # e.g., 1-5
    
    # Performance metrics
    bkt_change = Column(Float, nullable=True)

    # Relationship
    user = relationship("User", back_populates="interaction_logs")


class ExamSession(Base):
    """One row per user — stores exam start time for the server-side timer."""
    __tablename__ = "exam_sessions"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), unique=True, index=True)
    session_id = Column(String, index=True)           # UUID generated by frontend
    exam_start_ms = Column(BigInteger, nullable=False) # Unix ms when exam started
    exam_duration_ms = Column(BigInteger, default=lambda: settings.exam_duration_ms)
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="exam_session")


class UserActionLog(Base):
    """
    Fine-grained event log for every user interaction.
    action_type values:
        session_start, session_complete, timer_expired,
        question_view, question_navigate,
        choice_select, answer_submit, answer_skip,
        hint_request, hint_display, hint_feedback,
        intervention_offered, intervention_accepted, intervention_rejected,
        chat_message_sent, chat_response_received,
        profile_view, preference_update
    action_data: flexible JSON payload specific to each action_type.
    """
    __tablename__ = "user_action_logs"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), index=True)
    session_id = Column(String, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    action_type = Column(String, nullable=False, index=True)
    question_number = Column(Integer, nullable=True, index=True)
    action_data = Column(JSON, default=lambda: {})

    user = relationship("User", back_populates="action_logs")


class ChatLog(Base):
    """Stores every chat exchange (user message + tutor response) for analysis and context replay."""
    __tablename__ = "chat_logs"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), index=True)
    session_id = Column(String, index=True)
    question_number = Column(Integer, nullable=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    user_message = Column(Text, nullable=False)
    tutor_response = Column(Text, nullable=False)

    user = relationship("User", back_populates="chat_logs")


class InterventionLog(Base):
    """Tracks every proactive intervention offered and whether the student accepted it."""
    __tablename__ = "intervention_logs"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), index=True)
    session_id = Column(String, index=True)
    question_number = Column(Integer, nullable=False, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    time_on_question_ms = Column(Integer, nullable=False)
    mastery_at_trigger = Column(Float, nullable=True)
    accepted = Column(Boolean, nullable=True)  # None = offered, True = accepted, False = rejected

    user = relationship("User", back_populates="intervention_logs")
