# app/models/user.py
from sqlalchemy import (
    BigInteger,
    Column,
    Index,
    Integer,
    String,
    Float,
    DateTime,
    ForeignKey,
    JSON,
    Text,
    Boolean,
)
from sqlalchemy.orm import declarative_base, relationship
from datetime import datetime
from app.utils.config import settings


Base = declarative_base()


class User(Base):
    __tablename__ = "users"
    id = Column(String, primary_key=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    preferences = Column(JSON, default=lambda: {
        "hint_style_preference": "adaptive",
        "intervention_preference": "manual"
    })
    feedback_scores = Column(JSON, default=lambda: {})

    # Relationships
    skill_mastery = relationship("SkillMastery", back_populates="user", cascade="all, delete-orphan")
    interaction_logs = relationship("InteractionLog", back_populates="user", cascade="all, delete-orphan")
    exam_session = relationship("ExamSession", back_populates="user", uselist=False, cascade="all, delete-orphan")
    action_logs = relationship("UserActionLog", back_populates="user", cascade="all, delete-orphan")
    chat_logs = relationship("ChatLog", back_populates="user", cascade="all, delete-orphan")
    intervention_logs = relationship("InterventionLog", back_populates="user", cascade="all, delete-orphan")


class SkillMastery(Base):
    __tablename__ = "skill_mastery"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, ForeignKey("users.id"))
    skill_id = Column(String, index=True)
    mastery_level = Column(Float, default=settings.bkt_p_l0)
    consecutive_errors = Column(Integer, default=0)
    consecutive_skips = Column(Integer, default=0)
    last_updated = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationship
    user = relationship("User", back_populates="skill_mastery")


class InteractionLog(Base):
    __tablename__ = "interaction_logs"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, ForeignKey("users.id"))
    timestamp = Column(DateTime, default=datetime.utcnow)
    question_id = Column(Integer)
    skill = Column(String)
    attempt_key = Column(String, nullable=True)

    # Answer details
    user_answer = Column(Text, nullable=True)
    is_correct = Column(Boolean, nullable=True)
    time_taken_ms = Column(Integer, nullable=True)

    # Hint and feedback details (for a single interaction loop)
    hint_shown = Column(Boolean, default=False)
    hint_style_used = Column(String, nullable=True)
    hint_text = Column(Text, nullable=True) # <-- ADDED
    user_feedback_rating = Column(Integer, nullable=True) # e.g., 1-5
    
    # Performance metrics
    bkt_change = Column(Float, nullable=True)

    # Set by the admin UI's "Unlock question" repair. A voided row still exists
    # and is still exported for research - it is only excluded from the two
    # places that decide whether a question is locked: the server-side attempt
    # cap (app/endpoints/answer.py) and the history the frontend rebuilds
    # question state from (app/state_manager.py). Voiding rather than deleting
    # is deliberate: the only per-student remedies before this wiped the whole
    # interaction history, which made one mis-click mid-exam unrecoverable.
    voided_at = Column(DateTime, nullable=True)

    # Relationship
    user = relationship("User", back_populates="interaction_logs")

    __table_args__ = (
        Index(
            "ux_interaction_logs_user_question_attemptkey",
            "user_id", "question_id", "attempt_key",
            unique=True,
        ),
    )


class ExamSession(Base):
    """One row per user — stores exam start time for the server-side timer."""
    __tablename__ = "exam_sessions"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), unique=True, index=True)
    session_id = Column(String, index=True)           # UUID generated by frontend
    exam_start_ms = Column(BigInteger, nullable=False) # Unix ms when exam started
    exam_duration_ms = Column(BigInteger, default=lambda: settings.exam_duration_ms)
    submitted_at = Column(BigInteger, nullable=True)  # Unix ms when student submitted; None = in progress
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="exam_session")


class Participant(Base):
    """Pre-registered exam participants loaded from the manifest CSV.
    token is the identity — used as User.id once the student starts the exam."""
    __tablename__ = "participants"
    token = Column(String, primary_key=True, index=True)
    name = Column(String, nullable=False)
    identifier = Column(String, nullable=False, index=True)  # student ID / email
    group = Column(String, nullable=False)         # free_choice | adaptive
    intervention = Column(String, nullable=False)  # proactive | manual
    status = Column(String, nullable=False, default="unused")  # unused | active | completed
    active_session_id = Column(String, nullable=True)
    last_seen_at = Column(DateTime, nullable=True)
    started_at = Column(DateTime, nullable=True)


class UserActionLog(Base):
    """
    Fine-grained event log for every user interaction.

    The 19 action_type values the frontend actually emits, verified by grepping
    frontend/src for action_type:
        session_start, session_submit, session_expire, timer_warning,
        question_view, question_navigate,
        choice_select, answer_focus, answer_submit, answer_skip,
        hint_request, hint_display, hint_feedback,
        intervention_offer, intervention_accept, intervention_reject,
        chat_send,
        profile_view, preference_update

    An earlier version of this docstring listed names the app has never emitted
    (session_complete, timer_expired, intervention_offered/accepted/rejected,
    chat_message_sent, chat_response_received) and omitted answer_focus and
    timer_warning, so analysis queries written straight from it returned empty
    result sets with no indication why.

    The validation whitelist in app/endpoints/action_log.py is a different thing
    and is correct as it stands: it holds these canonical names AND keeps the
    old ones as explicit legacy aliases, so do not "fix" it to match this list.
    The tutor's chat reply is in chat_logs, not here.

    action_data: flexible JSON payload specific to each action_type.
    """
    __tablename__ = "user_action_logs"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), index=True)
    session_id = Column(String, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    action_type = Column(String, nullable=False, index=True)
    question_number = Column(Integer, nullable=True, index=True)
    action_data = Column(JSON, default=lambda: {})

    user = relationship("User", back_populates="action_logs")


class ChatLog(Base):
    """Stores every chat exchange (user message + tutor response) for analysis and context replay."""
    __tablename__ = "chat_logs"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), index=True)
    session_id = Column(String, index=True)
    question_number = Column(Integer, nullable=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    user_message = Column(Text, nullable=False)
    tutor_response = Column(Text, nullable=False)

    user = relationship("User", back_populates="chat_logs")


class InterventionLog(Base):
    """Tracks every proactive intervention offered and whether the student accepted it."""
    __tablename__ = "intervention_logs"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), index=True)
    session_id = Column(String, index=True)
    question_number = Column(Integer, nullable=False, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    time_on_question_ms = Column(Integer, nullable=False)
    mastery_at_trigger = Column(Float, nullable=True)
    reason = Column(String, nullable=True)  # time_spent | low_mastery | consecutive_errors | consecutive_skips
    accepted = Column(Boolean, nullable=True)  # None = offered, True = accepted, False = rejected

    user = relationship("User", back_populates="intervention_logs")


class LlmUsageLog(Base):
    """One row per accepted hint/chat call - what app/services/llm_quota.py
    counts against the per-user and global rolling-24h LLM spend caps
    (Stage 4.5). Reserved before the LLM call runs, so a call that then
    errors out still counts - it can still bill."""
    __tablename__ = "llm_usage_log"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    endpoint = Column(String, nullable=False)  # "hint" | "chat"
    created_at = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        Index("ix_llm_usage_log_user_created", "user_id", "created_at"),
        Index("ix_llm_usage_log_created", "created_at"),
    )


class AdminSetting(Base):
    """Key/value overrides an admin can change live, without an SSM session and
    an api restart.

    Only the two LLM spend caps use this today. It is a table rather than
    in-process state on purpose: process state would silently revert on
    `docker compose restart api`, and a raised cap quietly dropping back
    mid-exam would re-throttle students with nobody noticing. The admin Health
    and Exam tabs' in-memory counters make the opposite tradeoff, for the
    opposite reason - losing those on a restart costs nothing.
    """
    __tablename__ = "admin_settings"
    key = Column(String, primary_key=True)
    value = Column(String, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
