# app/endpoints/session.py
# Manages exam session timer — start time stored server-side, client reconciles on reconnect.
import time
from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

from app.models.user import ExamSession, User
from app.utils.config import settings
from app.utils.db import get_db
from app.utils.logger import logger

router = APIRouter(prefix="/session", tags=["Session"])


class SessionStartRequest(BaseModel):
    user_id: str
    session_id: str  # UUID generated by frontend


class SessionStartResponse(BaseModel):
    user_id: str
    session_id: str
    exam_start_ms: int
    exam_duration_ms: int
    ms_remaining: int


class SessionRemainingResponse(BaseModel):
    user_id: str
    exam_start_ms: int
    exam_duration_ms: int
    ms_remaining: int
    expired: bool


@router.post("/start", response_model=SessionStartResponse)
async def start_session(request: SessionStartRequest, db: AsyncSession = Depends(get_db)):
    """
    Idempotent — if session already exists for this user, returns the existing start time.
    This ensures page reloads don't reset the timer.
    """
    user_result = await db.execute(select(User).filter_by(id=request.user_id))
    user = user_result.scalars().first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    existing = await db.execute(select(ExamSession).filter_by(user_id=request.user_id))
    exam_session = existing.scalars().first()

    now_ms = int(time.time() * 1000)

    if exam_session is None:
        try:
            exam_session = ExamSession(
                user_id=request.user_id,
                session_id=request.session_id,
                exam_start_ms=now_ms,
                exam_duration_ms=settings.exam_duration_ms,
            )
            db.add(exam_session)
            await db.commit()
            await db.refresh(exam_session)
            logger.info(f"New exam session started for user {request.user_id}, session_id={request.session_id}")
        except IntegrityError:
            # Concurrent request already created the session (e.g. React StrictMode double-invoke)
            await db.rollback()
            result = await db.execute(select(ExamSession).filter_by(user_id=request.user_id))
            exam_session = result.scalars().first()
            logger.info(f"Race condition resolved — returning existing session for user {request.user_id}")
    else:
        logger.info(f"Returning existing exam session for user {request.user_id}")

    elapsed = now_ms - exam_session.exam_start_ms
    ms_remaining = max(0, exam_session.exam_duration_ms - elapsed)

    return SessionStartResponse(
        user_id=request.user_id,
        session_id=exam_session.session_id,
        exam_start_ms=exam_session.exam_start_ms,
        exam_duration_ms=exam_session.exam_duration_ms,
        ms_remaining=ms_remaining,
    )


@router.get("/{user_id}/remaining", response_model=SessionRemainingResponse)
async def get_remaining(user_id: str, db: AsyncSession = Depends(get_db)):
    """Returns time remaining for the user's exam session."""
    result = await db.execute(select(ExamSession).filter_by(user_id=user_id))
    exam_session = result.scalars().first()
    if not exam_session:
        raise HTTPException(status_code=404, detail="No active session for this user")

    now_ms = int(time.time() * 1000)
    elapsed = now_ms - exam_session.exam_start_ms
    ms_remaining = max(0, exam_session.exam_duration_ms - elapsed)

    return SessionRemainingResponse(
        user_id=user_id,
        exam_start_ms=exam_session.exam_start_ms,
        exam_duration_ms=exam_session.exam_duration_ms,
        ms_remaining=ms_remaining,
        expired=ms_remaining == 0,
    )
